-- 1000 Basic Questions Seed for Plivio Chat Quiz
INSERT INTO chat_questions (question, answer, category) VALUES

-- MATH: Addition (100)
('What is 1 + 1?', '2', 'math'),
('What is 2 + 3?', '5', 'math'),
('What is 5 + 7?', '12', 'math'),
('What is 8 + 6?', '14', 'math'),
('What is 9 + 4?', '13', 'math'),
('What is 12 + 15?', '27', 'math'),
('What is 20 + 30?', '50', 'math'),
('What is 25 + 25?', '50', 'math'),
('What is 14 + 18?', '32', 'math'),
('What is 33 + 17?', '50', 'math'),
('What is 45 + 55?', '100', 'math'),
('What is 7 + 8?', '15', 'math'),
('What is 11 + 13?', '24', 'math'),
('What is 19 + 21?', '40', 'math'),
('What is 50 + 50?', '100', 'math'),
('What is 6 + 9?', '15', 'math'),
('What is 16 + 24?', '40', 'math'),
('What is 38 + 12?', '50', 'math'),
('What is 47 + 53?', '100', 'math'),
('What is 3 + 4?', '7', 'math'),
('What is 22 + 28?', '50', 'math'),
('What is 15 + 35?', '50', 'math'),
('What is 60 + 40?', '100', 'math'),
('What is 75 + 25?', '100', 'math'),
('What is 13 + 7?', '20', 'math'),
('What is 100 + 200?', '300', 'math'),
('What is 150 + 150?', '300', 'math'),
('What is 99 + 1?', '100', 'math'),
('What is 88 + 12?', '100', 'math'),
('What is 77 + 23?', '100', 'math'),

-- MATH: Subtraction (70)
('What is 10 - 3?', '7', 'math'),
('What is 20 - 8?', '12', 'math'),
('What is 15 - 7?', '8', 'math'),
('What is 50 - 25?', '25', 'math'),
('What is 100 - 40?', '60', 'math'),
('What is 30 - 13?', '17', 'math'),
('What is 45 - 15?', '30', 'math'),
('What is 100 - 1?', '99', 'math'),
('What is 80 - 35?', '45', 'math'),
('What is 60 - 22?', '38', 'math'),
('What is 25 - 10?', '15', 'math'),
('What is 40 - 19?', '21', 'math'),
('What is 75 - 25?', '50', 'math'),
('What is 200 - 100?', '100', 'math'),
('What is 90 - 45?', '45', 'math'),
('What is 55 - 30?', '25', 'math'),
('What is 66 - 33?', '33', 'math'),
('What is 100 - 55?', '45', 'math'),
('What is 88 - 44?', '44', 'math'),
('What is 70 - 35?', '35', 'math'),

-- MATH: Multiplication (70)
('What is 2 × 3?', '6', 'math'),
('What is 4 × 5?', '20', 'math'),
('What is 6 × 7?', '42', 'math'),
('What is 8 × 9?', '72', 'math'),
('What is 3 × 3?', '9', 'math'),
('What is 5 × 5?', '25', 'math'),
('What is 10 × 10?', '100', 'math'),
('What is 7 × 8?', '56', 'math'),
('What is 6 × 6?', '36', 'math'),
('What is 9 × 9?', '81', 'math'),
('What is 4 × 4?', '16', 'math'),
('What is 2 × 10?', '20', 'math'),
('What is 3 × 7?', '21', 'math'),
('What is 5 × 8?', '40', 'math'),
('What is 4 × 6?', '24', 'math'),
('What is 2 × 8?', '16', 'math'),
('What is 3 × 9?', '27', 'math'),
('What is 7 × 7?', '49', 'math'),
('What is 6 × 8?', '48', 'math'),
('What is 5 × 9?', '45', 'math'),
('What is 11 × 11?', '121', 'math'),
('What is 12 × 12?', '144', 'math'),
('What is 10 × 5?', '50', 'math'),
('What is 2 × 2?', '4', 'math'),
('What is 3 × 5?', '15', 'math'),

-- MATH: Division (50)
('What is 10 ÷ 2?', '5', 'math'),
('What is 20 ÷ 4?', '5', 'math'),
('What is 36 ÷ 6?', '6', 'math'),
('What is 100 ÷ 10?', '10', 'math'),
('What is 81 ÷ 9?', '9', 'math'),
('What is 64 ÷ 8?', '8', 'math'),
('What is 49 ÷ 7?', '7', 'math'),
('What is 25 ÷ 5?', '5', 'math'),
('What is 16 ÷ 4?', '4', 'math'),
('What is 9 ÷ 3?', '3', 'math'),
('What is 50 ÷ 5?', '10', 'math'),
('What is 72 ÷ 8?', '9', 'math'),
('What is 42 ÷ 7?', '6', 'math'),
('What is 30 ÷ 6?', '5', 'math'),
('What is 48 ÷ 6?', '8', 'math'),
('What is 56 ÷ 8?', '7', 'math'),
('What is 40 ÷ 8?', '5', 'math'),
('What is 21 ÷ 7?', '3', 'math'),
('What is 18 ÷ 3?', '6', 'math'),
('What is 24 ÷ 4?', '6', 'math'),

-- MATH: Mixed (30)
('What is half of 100?', '50', 'math'),
('What is half of 50?', '25', 'math'),
('What is double 15?', '30', 'math'),
('What is double 25?', '50', 'math'),
('What is 10% of 100?', '10', 'math'),
('What is 50% of 80?', '40', 'math'),
('What is 25% of 100?', '25', 'math'),
('What is the square root of 25?', '5', 'math'),
('What is the square root of 36?', '6', 'math'),
('What is the square root of 49?', '7', 'math'),
('What is the square root of 64?', '8', 'math'),
('What is the square root of 81?', '9', 'math'),
('What is the square root of 100?', '10', 'math'),
('What is 2 to the power of 3?', '8', 'math'),
('What is 2 to the power of 4?', '16', 'math'),
('What is 2 to the power of 5?', '32', 'math'),
('What is 3 to the power of 2?', '9', 'math'),
('What is 4 to the power of 2?', '16', 'math'),
('How many sides does a triangle have?', '3', 'math'),
('How many sides does a square have?', '4', 'math'),
('How many sides does a pentagon have?', '5', 'math'),
('How many sides does a hexagon have?', '6', 'math'),
('How many sides does a octagon have?', '8', 'math'),
('How many degrees in a right angle?', '90', 'math'),
('How many degrees in a straight line?', '180', 'math'),
('How many degrees in a full circle?', '360', 'math'),
('What is the perimeter of a square with side 5?', '20', 'math'),
('What is the area of a square with side 4?', '16', 'math'),
('How many minutes in an hour?', '60', 'math'),
('How many hours in a day?', '24', 'math'),

-- PHILIPPINES (100)
('What is the capital of the Philippines?', 'Manila', 'philippines'),
('What is the national hero of the Philippines?', 'Jose Rizal', 'philippines'),
('What is the currency of the Philippines?', 'Peso', 'philippines'),
('What language is officially spoken in the Philippines?', 'Filipino', 'philippines'),
('How many islands does the Philippines have?', '7641', 'philippines'),
('What is the largest island in the Philippines?', 'Luzon', 'philippines'),
('What is the second largest island in the Philippines?', 'Mindanao', 'philippines'),
('What is the national flower of the Philippines?', 'Sampaguita', 'philippines'),
('What is the national bird of the Philippines?', 'Philippine Eagle', 'philippines'),
('What is the national animal of the Philippines?', 'Carabao', 'philippines'),
('What is the national fruit of the Philippines?', 'Mango', 'philippines'),
('What is the national tree of the Philippines?', 'Narra', 'philippines'),
('What is the tallest volcano in the Philippines?', 'Mount Apo', 'philippines'),
('What is the longest river in the Philippines?', 'Cagayan River', 'philippines'),
('What is the largest lake in the Philippines?', 'Laguna de Bay', 'philippines'),
('What city is known as the Summer Capital of the Philippines?', 'Baguio', 'philippines'),
('What is the nickname of Cebu City?', 'Queen City of the South', 'philippines'),
('In what year did the Philippines gain independence?', '1946', 'philippines'),
('Who was the first President of the Philippines?', 'Emilio Aguinaldo', 'philippines'),
('What is the national sport of the Philippines?', 'Arnis', 'philippines'),
('What sea is to the west of the Philippines?', 'South China Sea', 'philippines'),
('What ocean is to the east of the Philippines?', 'Pacific Ocean', 'philippines'),
('What is the famous rice terraces in the Philippines?', 'Banaue Rice Terraces', 'philippines'),
('What province is Boracay island located in?', 'Aklan', 'philippines'),
('What is the smallest province in the Philippines?', 'Batanes', 'philippines'),
('What is the most populated city in the Philippines?', 'Quezon City', 'philippines'),
('What is the Philippine flag color on top?', 'Blue', 'philippines'),
('How many stars are on the Philippine flag?', '3', 'philippines'),
('What does the sun on the Philippine flag represent?', 'The 8 provinces', 'philippines'),
('What is the national gem of the Philippines?', 'South Sea Pearl', 'philippines'),
('What is adobo?', 'A Filipino dish', 'philippines'),
('What is the Filipino word for thank you?', 'Salamat', 'philippines'),
('What is the Filipino word for yes?', 'Oo', 'philippines'),
('What is the Filipino word for no?', 'Hindi', 'philippines'),
('What is the Filipino word for friend?', 'Kaibigan', 'philippines'),
('What is the Filipino word for love?', 'Pag-ibig', 'philippines'),
('What is the Filipino word for water?', 'Tubig', 'philippines'),
('What is the Filipino word for food?', 'Pagkain', 'philippines'),
('What is the Filipino word for house?', 'Bahay', 'philippines'),
('What is the Filipino word for family?', 'Pamilya', 'philippines'),
('What festival is celebrated in Cebu every January?', 'Sinulog', 'philippines'),
('What festival is celebrated in Iloilo?', 'Dinagyang', 'philippines'),
('What city is known for the MassKara Festival?', 'Bacolod', 'philippines'),
('What is the GCash parent company?', 'Globe Telecom', 'philippines'),
('What is the largest mall in the Philippines?', 'SM Mall of Asia', 'philippines'),
('What Philippine city is known as the City of Pines?', 'Baguio', 'philippines'),
('What is Palawan famous for?', 'Beautiful beaches and nature', 'philippines'),
('What is the name of the Philippine underground river?', 'Puerto Princesa Underground River', 'philippines'),
('What is the Chocolate Hills located in?', 'Bohol', 'philippines'),
('What is the name of the smallest primate in the Philippines?', 'Tarsier', 'philippines'),

-- SCIENCE (100)
('What is the chemical symbol for water?', 'H2O', 'science'),
('What is the chemical symbol for oxygen?', 'O', 'science'),
('What is the chemical symbol for gold?', 'Au', 'science'),
('What is the chemical symbol for silver?', 'Ag', 'science'),
('What is the chemical symbol for iron?', 'Fe', 'science'),
('What planet is closest to the Sun?', 'Mercury', 'science'),
('What is the largest planet in our solar system?', 'Jupiter', 'science'),
('What planet is known as the Red Planet?', 'Mars', 'science'),
('How many planets are in our solar system?', '8', 'science'),
('What is the center of our solar system?', 'The Sun', 'science'),
('What is the force that pulls objects toward Earth?', 'Gravity', 'science'),
('What is the speed of light approximately?', '300,000 km/s', 'science'),
('What gas do plants absorb during photosynthesis?', 'Carbon dioxide', 'science'),
('What gas do plants release during photosynthesis?', 'Oxygen', 'science'),
('What is the powerhouse of the cell?', 'Mitochondria', 'science'),
('How many bones are in the adult human body?', '206', 'science'),
('What is the largest organ in the human body?', 'Skin', 'science'),
('What is the hardest natural substance?', 'Diamond', 'science'),
('What is the boiling point of water in Celsius?', '100', 'science'),
('What is the freezing point of water in Celsius?', '0', 'science'),
('How many chambers does the human heart have?', '4', 'science'),
('What is DNA short for?', 'Deoxyribonucleic acid', 'science'),
('What is the most abundant gas in Earth''s atmosphere?', 'Nitrogen', 'science'),
('What layer of Earth do we live on?', 'Crust', 'science'),
('What causes earthquakes?', 'Tectonic plates', 'science'),
('What is the unit of electric current?', 'Ampere', 'science'),
('What is the unit of force?', 'Newton', 'science'),
('What is H2O2?', 'Hydrogen peroxide', 'science'),
('What is NaCl?', 'Salt', 'science'),
('What is CO2?', 'Carbon dioxide', 'science'),
('What organ filters blood in the body?', 'Kidney', 'science'),
('What organ pumps blood in the body?', 'Heart', 'science'),
('What is the study of plants called?', 'Botany', 'science'),
('What is the study of animals called?', 'Zoology', 'science'),
('What is the study of the stars called?', 'Astronomy', 'science'),
('What is the study of the Earth called?', 'Geology', 'science'),
('What is the study of living things called?', 'Biology', 'science'),
('What is the study of matter and energy called?', 'Physics', 'science'),
('What is the study of chemicals called?', 'Chemistry', 'science'),
('How many teeth does an adult human have?', '32', 'science'),
('What is the closest star to Earth?', 'The Sun', 'science'),
('How long does it take Earth to orbit the Sun?', '365 days', 'science'),
('How long does it take the Moon to orbit Earth?', '28 days', 'science'),
('What is the name of Earth''s natural satellite?', 'Moon', 'science'),
('What is the hottest planet in our solar system?', 'Venus', 'science'),
('What is the smallest planet in our solar system?', 'Mercury', 'science'),
('What is the largest ocean on Earth?', 'Pacific Ocean', 'science'),
('What is the tallest mountain on Earth?', 'Mount Everest', 'science'),
('What is the longest river on Earth?', 'Nile', 'science'),
('What is the largest continent?', 'Asia', 'science'),

-- GEOGRAPHY - WORLD (100)
('What is the capital of Japan?', 'Tokyo', 'geography'),
('What is the capital of France?', 'Paris', 'geography'),
('What is the capital of the United States?', 'Washington D.C.', 'geography'),
('What is the capital of the United Kingdom?', 'London', 'geography'),
('What is the capital of China?', 'Beijing', 'geography'),
('What is the capital of Australia?', 'Canberra', 'geography'),
('What is the capital of Canada?', 'Ottawa', 'geography'),
('What is the capital of Germany?', 'Berlin', 'geography'),
('What is the capital of Italy?', 'Rome', 'geography'),
('What is the capital of Spain?', 'Madrid', 'geography'),
('What is the capital of Brazil?', 'Brasilia', 'geography'),
('What is the capital of Russia?', 'Moscow', 'geography'),
('What is the capital of South Korea?', 'Seoul', 'geography'),
('What is the capital of Indonesia?', 'Jakarta', 'geography'),
('What is the capital of Thailand?', 'Bangkok', 'geography'),
('What is the capital of India?', 'New Delhi', 'geography'),
('What is the capital of Egypt?', 'Cairo', 'geography'),
('What is the capital of Mexico?', 'Mexico City', 'geography'),
('What is the capital of Argentina?', 'Buenos Aires', 'geography'),
('What is the capital of Saudi Arabia?', 'Riyadh', 'geography'),
('What continent is Egypt in?', 'Africa', 'geography'),
('What continent is Brazil in?', 'South America', 'geography'),
('What continent is Japan in?', 'Asia', 'geography'),
('What continent is Australia in?', 'Australia', 'geography'),
('What continent is France in?', 'Europe', 'geography'),
('How many continents are there?', '7', 'geography'),
('What is the smallest country in the world?', 'Vatican City', 'geography'),
('What is the largest country in the world by area?', 'Russia', 'geography'),
('What is the most populated country in the world?', 'India', 'geography'),
('What ocean is between America and Europe?', 'Atlantic Ocean', 'geography'),
('What is the capital of Singapore?', 'Singapore', 'geography'),
('What is the capital of Malaysia?', 'Kuala Lumpur', 'geography'),
('What is the capital of Vietnam?', 'Hanoi', 'geography'),
('What is the capital of Cambodia?', 'Phnom Penh', 'geography'),
('What is the capital of Myanmar?', 'Naypyidaw', 'geography'),
('What is the capital of Pakistan?', 'Islamabad', 'geography'),
('What is the capital of Nigeria?', 'Abuja', 'geography'),
('What is the capital of South Africa?', 'Pretoria', 'geography'),
('What is the capital of Kenya?', 'Nairobi', 'geography'),
('What is the capital of UAE?', 'Abu Dhabi', 'geography'),
('Which country has the most land area in Southeast Asia?', 'Indonesia', 'geography'),
('What is the currency of Japan?', 'Yen', 'geography'),
('What is the currency of the United Kingdom?', 'Pound', 'geography'),
('What is the currency of the European Union?', 'Euro', 'geography'),
('What is the currency of the United States?', 'Dollar', 'geography'),
('What is the currency of China?', 'Yuan', 'geography'),
('What is the currency of South Korea?', 'Won', 'geography'),
('What is the currency of Thailand?', 'Baht', 'geography'),
('What is the currency of Japan?', 'Yen', 'geography'),
('What is the currency of India?', 'Rupee', 'geography'),

-- HISTORY (80)
('In what year did World War II end?', '1945', 'history'),
('In what year did World War I begin?', '1914', 'history'),
('Who was the first man to walk on the Moon?', 'Neil Armstrong', 'history'),
('In what year did man first land on the Moon?', '1969', 'history'),
('Who invented the telephone?', 'Alexander Graham Bell', 'history'),
('Who invented the light bulb?', 'Thomas Edison', 'history'),
('Who discovered gravity?', 'Isaac Newton', 'history'),
('Who painted the Mona Lisa?', 'Leonardo da Vinci', 'history'),
('Who wrote Romeo and Juliet?', 'William Shakespeare', 'history'),
('Who was the first President of the United States?', 'George Washington', 'history'),
('In what year did Christopher Columbus arrive in America?', '1492', 'history'),
('What ancient wonder was in Egypt?', 'Pyramids of Giza', 'history'),
('Who was Albert Einstein?', 'A physicist', 'history'),
('What did Alexander Fleming discover?', 'Penicillin', 'history'),
('In what year did the Berlin Wall fall?', '1989', 'history'),
('Who invented the airplane?', 'Wright Brothers', 'history'),
('What empire did Julius Caesar lead?', 'Roman Empire', 'history'),
('Who was the first woman to win a Nobel Prize?', 'Marie Curie', 'history'),
('In what country did the Industrial Revolution begin?', 'England', 'history'),
('What was the name of the first artificial satellite?', 'Sputnik', 'history'),
('Who was Napoleon Bonaparte?', 'A French emperor', 'history'),
('What year was the Titanic shipwreck?', '1912', 'history'),
('Who invented the internet?', 'Tim Berners-Lee', 'history'),
('What country did Hitler lead?', 'Germany', 'history'),
('In what year did the French Revolution begin?', '1789', 'history'),
('Who was the first Filipino to go to space?', 'No Filipino has gone to space yet', 'history'),
('What year did Jose Rizal die?', '1896', 'history'),
('What is Rizal''s first novel?', 'Noli Me Tangere', 'history'),
('What is Rizal''s second novel?', 'El Filibusterismo', 'history'),
('What is the EDSA Revolution also called?', 'People Power Revolution', 'history'),

-- GENERAL KNOWLEDGE (100)
('How many colors are in a rainbow?', '7', 'general'),
('What color do you get when you mix red and blue?', 'Purple', 'general'),
('What color do you get when you mix red and yellow?', 'Orange', 'general'),
('What color do you get when you mix blue and yellow?', 'Green', 'general'),
('How many days are in a week?', '7', 'general'),
('How many months are in a year?', '12', 'general'),
('How many days are in a year?', '365', 'general'),
('How many seconds in a minute?', '60', 'general'),
('How many minutes in a day?', '1440', 'general'),
('What is the first month of the year?', 'January', 'general'),
('What is the last month of the year?', 'December', 'general'),
('What month has 28 or 29 days?', 'February', 'general'),
('What day comes after Monday?', 'Tuesday', 'general'),
('What day comes after Friday?', 'Saturday', 'general'),
('What is the first day of the week?', 'Sunday', 'general'),
('How many legs does a spider have?', '8', 'general'),
('How many legs does an insect have?', '6', 'general'),
('How many legs does a dog have?', '4', 'general'),
('What sound does a dog make?', 'Bark', 'general'),
('What sound does a cat make?', 'Meow', 'general'),
('What sound does a cow make?', 'Moo', 'general'),
('What animal is known as man''s best friend?', 'Dog', 'general'),
('What is the fastest land animal?', 'Cheetah', 'general'),
('What is the largest land animal?', 'Elephant', 'general'),
('What is the tallest animal?', 'Giraffe', 'general'),
('What is the largest animal in the world?', 'Blue Whale', 'general'),
('What do bees produce?', 'Honey', 'general'),
('What do cows produce?', 'Milk', 'general'),
('What do hens produce?', 'Eggs', 'general'),
('What do silkworms produce?', 'Silk', 'general'),
('What is the opposite of hot?', 'Cold', 'general'),
('What is the opposite of day?', 'Night', 'general'),
('What is the opposite of big?', 'Small', 'general'),
('What is the opposite of happy?', 'Sad', 'general'),
('What is the opposite of fast?', 'Slow', 'general'),
('What is the opposite of strong?', 'Weak', 'general'),
('What is the opposite of rich?', 'Poor', 'general'),
('What is the opposite of old?', 'Young', 'general'),
('What is the opposite of black?', 'White', 'general'),
('What is the opposite of north?', 'South', 'general'),
('What shape is a wheel?', 'Circle', 'general'),
('What shape is a book?', 'Rectangle', 'general'),
('What shape is a pizza slice?', 'Triangle', 'general'),
('What shape is a die?', 'Cube', 'general'),
('How many letters are in the English alphabet?', '26', 'general'),
('What is the first letter of the alphabet?', 'A', 'general'),
('What is the last letter of the alphabet?', 'Z', 'general'),
('What vowels are in the English alphabet?', 'A E I O U', 'general'),
('How many vowels are in the English alphabet?', '5', 'general'),
('What number comes after 9?', '10', 'general'),

-- TECHNOLOGY (50)
('What does CPU stand for?', 'Central Processing Unit', 'technology'),
('What does RAM stand for?', 'Random Access Memory', 'technology'),
('What does USB stand for?', 'Universal Serial Bus', 'technology'),
('What does WiFi stand for?', 'Wireless Fidelity', 'technology'),
('What does ATM stand for?', 'Automated Teller Machine', 'technology'),
('What does PDF stand for?', 'Portable Document Format', 'technology'),
('What does HTML stand for?', 'HyperText Markup Language', 'technology'),
('What does URL stand for?', 'Uniform Resource Locator', 'technology'),
('What does AI stand for?', 'Artificial Intelligence', 'technology'),
('What does GPS stand for?', 'Global Positioning System', 'technology'),
('What company makes the iPhone?', 'Apple', 'technology'),
('What company makes the Android system?', 'Google', 'technology'),
('What is the most popular search engine?', 'Google', 'technology'),
('What social media platform uses the bird logo?', 'Twitter', 'technology'),
('What social media platform uses the camera logo?', 'Instagram', 'technology'),
('What does SMS stand for?', 'Short Message Service', 'technology'),
('What does IT stand for?', 'Information Technology', 'technology'),
('What is www short for?', 'World Wide Web', 'technology'),
('What does LAN stand for?', 'Local Area Network', 'technology'),
('What does VPN stand for?', 'Virtual Private Network', 'technology'),
('Who founded Microsoft?', 'Bill Gates', 'technology'),
('Who founded Apple?', 'Steve Jobs', 'technology'),
('Who founded Facebook?', 'Mark Zuckerberg', 'technology'),
('What programming language is Python named after?', 'Monty Python', 'technology'),
('What does HTTP stand for?', 'HyperText Transfer Protocol', 'technology'),

-- ENGLISH / VOCABULARY (100)
('What is a synonym for happy?', 'Joyful', 'english'),
('What is a synonym for sad?', 'Unhappy', 'english'),
('What is a synonym for big?', 'Large', 'english'),
('What is a synonym for small?', 'Tiny', 'english'),
('What is a synonym for fast?', 'Quick', 'english'),
('What is a synonym for beautiful?', 'Pretty', 'english'),
('What is a synonym for angry?', 'Mad', 'english'),
('What is a synonym for tired?', 'Exhausted', 'english'),
('What is a synonym for smart?', 'Intelligent', 'english'),
('What is a synonym for brave?', 'Courageous', 'english'),
('What is a plural of child?', 'Children', 'english'),
('What is a plural of mouse?', 'Mice', 'english'),
('What is a plural of tooth?', 'Teeth', 'english'),
('What is a plural of foot?', 'Feet', 'english'),
('What is a plural of man?', 'Men', 'english'),
('What is a plural of woman?', 'Women', 'english'),
('What is a plural of person?', 'People', 'english'),
('What is a plural of leaf?', 'Leaves', 'english'),
('What is a plural of knife?', 'Knives', 'english'),
('What is a plural of life?', 'Lives', 'english'),
('What part of speech is a word that describes a noun?', 'Adjective', 'english'),
('What part of speech is a word that describes a verb?', 'Adverb', 'english'),
('What part of speech is a word that names a person place or thing?', 'Noun', 'english'),
('What part of speech is a word that shows action?', 'Verb', 'english'),
('What is the past tense of run?', 'Ran', 'english'),
('What is the past tense of eat?', 'Ate', 'english'),
('What is the past tense of go?', 'Went', 'english'),
('What is the past tense of see?', 'Saw', 'english'),
('What is the past tense of come?', 'Came', 'english'),
('What is the past tense of buy?', 'Bought', 'english'),
('What is the past tense of write?', 'Wrote', 'english'),
('What is the past tense of speak?', 'Spoke', 'english'),
('What is the past tense of take?', 'Took', 'english'),
('What is the past tense of give?', 'Gave', 'english'),
('What does "abundant" mean?', 'More than enough', 'english'),
('What does "ancient" mean?', 'Very old', 'english'),
('What does "brave" mean?', 'Showing courage', 'english'),
('What does "calm" mean?', 'Peaceful and quiet', 'english'),
('What does "delicate" mean?', 'Fragile or sensitive', 'english'),
('What does "enormous" mean?', 'Very large', 'english'),
('What does "fragile" mean?', 'Easily broken', 'english'),
('What does "generous" mean?', 'Willing to give', 'english'),
('What does "humble" mean?', 'Not proud or arrogant', 'english'),
('What does "innocent" mean?', 'Not guilty', 'english'),
('What letter comes after D in the alphabet?', 'E', 'english'),
('What letter comes before Z in the alphabet?', 'Y', 'english'),
('How many syllables does "beautiful" have?', '3', 'english'),
('How many syllables does "education" have?', '4', 'english'),
('What is the longest word with all vowels in order?', 'Abstemious', 'english'),

-- SPORTS (50)
('How many players are on a basketball team on court?', '5', 'sports'),
('How many players are on a soccer team on field?', '11', 'sports'),
('How many players are on a volleyball team?', '6', 'sports'),
('How many players are on a baseball team?', '9', 'sports'),
('How many innings are in a baseball game?', '9', 'sports'),
('How many quarters are in a basketball game?', '4', 'sports'),
('How many halves are in a soccer game?', '2', 'sports'),
('How many sets are in a volleyball game?', '5', 'sports'),
('What sport uses a racket and shuttlecock?', 'Badminton', 'sports'),
('What sport uses a bat and ball on a diamond?', 'Baseball', 'sports'),
('What sport is played on a court with a net and rackets?', 'Tennis', 'sports'),
('What sport involves swimming?', 'Swimming', 'sports'),
('What sport involves running 42km?', 'Marathon', 'sports'),
('How many points is a basketball free throw worth?', '1', 'sports'),
('How many points is a basketball three-pointer worth?', '3', 'sports'),
('What country invented basketball?', 'United States', 'sports'),
('What country invented badminton?', 'England', 'sports'),
('What sport is Manny Pacquiao famous for?', 'Boxing', 'sports'),
('How many players are on each side in a tennis singles match?', '1', 'sports'),
('What is the national sport of the Philippines?', 'Arnis', 'sports'),

-- FOOD (50)
('What is the main ingredient in bread?', 'Flour', 'food'),
('What fruit is known as the king of fruits?', 'Durian', 'food'),
('What is the most consumed grain in the Philippines?', 'Rice', 'food'),
('What vegetable makes you cry when you cut it?', 'Onion', 'food'),
('What is the yellow fruit monkeys love?', 'Banana', 'food'),
('What is the red fruit that is actually a vegetable?', 'Tomato', 'food'),
('What do you call the outer layer of bread?', 'Crust', 'food'),
('What is made from fermented grapes?', 'Wine', 'food'),
('What is the main ingredient in chocolate?', 'Cacao', 'food'),
('What food comes from chickens?', 'Eggs', 'food'),
('What is the Filipino rice cake called?', 'Kakanin', 'food'),
('What is sinigang?', 'A Filipino sour soup', 'food'),
('What is lechon?', 'Roasted pig', 'food'),
('What is lumpia?', 'Filipino spring roll', 'food'),
('What is halo-halo?', 'A Filipino mixed dessert', 'food'),
('What is balut?', 'A fertilized duck egg', 'food'),
('What vitamin is found in oranges?', 'Vitamin C', 'food'),
('What mineral is found in milk?', 'Calcium', 'food'),
('What gas makes soda bubbly?', 'Carbon dioxide', 'food'),
('What is the main ingredient in tofu?', 'Soybeans', 'food');
